version: '3.6'
services:
  app :
    container_name: provisioned-api
    hostname: provisioned-api
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOST_FROM: dns
    ports:
      - 8080:8080